[project]
name = "rtichoke-blog-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rtichoke>=0.1.18",
]

[dependency-groups]
dev = []
